#                                                   Matrices


NAME = Mayank Chandra Joshi

Roll No. = CSC/20/31

UNIVERSITY ROLL NO.= 20059570023


In [20]:
# (a) Perform basic operations on matrices:

In [21]:
#(i) addition of two matrices

import numpy as np  # importing numpy library
mat1 = np.random.randint(30, size=(3,3))
mat2 = np.random.randint(20, size=(3,3))
print("Matrix1 = \n",mat1)
print("\nMatrix2 = \n",mat2)
print("\nAddition = \n",mat1+mat2) #addition

Matrix1 = 
 [[28 10 18]
 [ 6 14  4]
 [ 8  0  2]]

Matrix2 = 
 [[ 6  7 15]
 [ 8 18 15]
 [10  7  2]]

Addition = 
 [[34 17 33]
 [14 32 19]
 [18  7  4]]


In [22]:
#(ii) subtraction of two matrices

print("\nSubtraction = \n",mat1-mat2) # subtraction


Subtraction = 
 [[ 22   3   3]
 [ -2  -4 -11]
 [ -2  -7   0]]


In [23]:
#(iii) multiplication of two matrices

print("\nMultiplication = \n",np.dot(mat1,mat2))  #multiplication


Multiplication = 
 [[428 502 606]
 [188 322 308]
 [ 68  70 124]]


In [24]:
#(iv) transpose of a matrix

print("\nTranspose = \n",mat1.transpose())  #transpose


Transpose = 
 [[28  6  8]
 [10 14  0]
 [18  4  2]]


In [25]:
# (b) Display specific roes and columns of a matrix:

In [26]:
print("\nSpecific row & column = \n",mat1[0:2, 1:3]) 


Specific row & column = 
 [[10 18]
 [14  4]]
