#                                                FILE HANDLING                                          
    

NAME = Mayank Chandra Joshi

Roll No. = CSC/20/31

UNIVERSITY ROLL NO.= 20059570023


In [15]:
# (a) Load data from a text file 

In [16]:
#Text file data converted to integer data type

import numpy as np
import pandas as pd
file = np.loadtxt("f1.txt",dtype = int)
print(file)

[[23 12 23]
 [34 44 83]
 [45 34 65]]


In [17]:
# (i) size of matrix

len(file)

3

In [18]:
# (ii) size/length of a particular row/column

print("Size of 2nd column :",len(file[:,2]))
print("Size of 0th row :",len(file[0]))

Size of 2nd column : 3
Size of 0th row : 3


In [19]:

# (c) Store matrix data to a text file

In [20]:
import numpy as np
import pandas as pd

d1 = np.random.randint(1,20,9).reshape(3,3)
d1

array([[ 3, 16, 13],
       [ 8,  5,  6],
       [ 6, 19, 11]])

In [21]:
np.savetxt("f2c.txt",d1)
content = np.loadtxt("f2c.txt")
print("\nContent in file1.txt:\n",content)


Content in file1.txt:
 [[ 3. 16. 13.]
 [ 8.  5.  6.]
 [ 6. 19. 11.]]
