#                                             Array and Metrices


NAME = Mayank Chandra Joshi

Roll No. = CSC/20/31

University Roll No.= 20059570023


In [20]:
# (a) Create array

# i)   with specific values(single and multidimensional)
# ii)  with all ones
# iii) with all zeroes
# iv)  with random values
# v)   with all elements zereos except diagonal(diagonal matrix);  


import numpy as np

print("Single dimensional array :\n{arr}\n".format(arr=np.array([2,3,4,2,3])))
print("Multi dimensional array :\n{arr}\n".format(arr=np.array([2,3,4,2,3,10]).reshape(2,3)))
print("Array of ones :\n{arr}\n".format(arr=np.ones(10, dtype=int)))
print("Array of zeroes :\n{arr}\n".format(arr=np.zeros(10, dtype=int)))
print("Array with random values :\n{arr}\n".format(arr=np.random.randint(9,size=10)))
print("Diagonal array :\n{arr}\n".format(arr=np.diag([4,5,3])))

Single dimensional array :
[2 3 4 2 3]

Multi dimensional array :
[[ 2  3  4]
 [ 2  3 10]]

Array of ones :
[1 1 1 1 1 1 1 1 1 1]

Array of zeroes :
[0 0 0 0 0 0 0 0 0 0]

Array with random values :
[7 4 2 7 6 7 3 2 2 4]

Diagonal array :
[[4 0 0]
 [0 5 0]
 [0 0 3]]



In [21]:
# (b) Perform matrix operation 

import numpy as np  
mat = np.random.randint(10, size=(4,6)) 
print("Matrix = \n",mat)

# i) convert matrix data to absolute value
print("\n Absolute values = \n",np.absolute(mat))

#(ii) negative of a matrix
print("\n Negative of matrix = \n", mat*-1)


Matrix = 
 [[7 8 8 3 1 4]
 [7 3 2 3 0 7]
 [3 3 4 2 9 2]
 [5 0 2 9 7 1]]

 Absolute values = 
 [[7 8 8 3 1 4]
 [7 3 2 3 0 7]
 [3 3 4 2 9 2]
 [5 0 2 9 7 1]]

 Negative of matrix = 
 [[-7 -8 -8 -3 -1 -4]
 [-7 -3 -2 -3  0 -7]
 [-3 -3 -4 -2 -9 -2]
 [-5  0 -2 -9 -7 -1]]


In [22]:
#(iii) add rows & columns from a matrix
row = [0,0,0,0,0,0]
col = [1,1,1,1]
print("\n Add a row  = \n", np.append(mat, [row], axis=0)) 

print("\n Add a column =\n ", np.insert(mat, 3, col, axis=1))


 Add a row  = 
 [[7 8 8 3 1 4]
 [7 3 2 3 0 7]
 [3 3 4 2 9 2]
 [5 0 2 9 7 1]
 [0 0 0 0 0 0]]

 Add a column =
  [[7 8 8 1 3 1 4]
 [7 3 2 1 3 0 7]
 [3 3 4 1 2 9 2]
 [5 0 2 1 9 7 1]]


In [23]:
#(iv) remove rows & columns from a matrix

print("\n Matrix after removing row = \n", np.delete(mat, 1, 0))           # Using delete function
print("\n Matrix after removing column = \n", np.delete(mat, 1, 1))  


 Matrix after removing row = 
 [[7 8 8 3 1 4]
 [3 3 4 2 9 2]
 [5 0 2 9 7 1]]

 Matrix after removing column = 
 [[7 8 3 1 4]
 [7 2 3 0 7]
 [3 4 2 9 2]
 [5 2 9 7 1]]


In [24]:
#(v) find maximun & minimum value in matrix or in row in column

print("\nMaximum value in matrix :-",mat.max())    
print("Minimum value in matrix :",mat.min())       

print("\nMaximum value in columns :",mat.max(0))  
print("Minimum value in columns :",mat.min(0))

print("\nMaximum value in rows :",mat.max(1))
print("Minimum value in rows :",mat.min(1))     


Maximum value in matrix :- 9
Minimum value in matrix : 0

Maximum value in columns : [7 8 8 9 9 7]
Minimum value in columns : [3 0 2 2 0 1]

Maximum value in rows : [8 7 9 9]
Minimum value in rows : [1 0 2 0]


In [25]:
#(v) find sum of all elements in matrix 
print("\nSum of all elements = ",np.sum(mat)) 


Sum of all elements =  100
